### ISSUE TITLE
rdfs:label for Work/Instance has trailing (ISBD) punctuation; should use bf:mainTitle value

### ISSUE THREAD

**Issue by dbs** [lcnetdev/marc2bibframe2#104]
A conversion of `test/data/ConvSpec-200-247not240-Titles/marc245.xml` generates `rdfs:label` statements for `bf:Work` entities; these `rdfs:label` values contain trailing (ISBD) punctuation.

As BIBFRAME may be used in contexts where consumers just grab `rdfs:label` as a handy description of the resource rather than drilling down through `bf:title/bf:Title/bf:mainTitle`, I suggest we reuse the `bf:mainTitle` value that has gone through the `chopPunctuation chopString` treatment.

We can additionally trim the trailing punctuation from the bflc:titleSortKey.

If a rationale for maintaining the ISBD in the generated BIBFRAME was to ease the roundtripping to MARC, I suspect it is easier to generate the desired punctuation as part of the BIBFRAME to MARC transform.

**Comment by wafschneider** [comment]
Hi, @dbs -- I think this concern is at least partially addressed by commit 3d6d253e5d232b9cbd769ddd6ae587a8f1045c22 in the v1.4.0 branch. Can you take a look and see if it means your concerns?

**Comment by dbs** [comment]
Looks good to me!
