### ISSUE TITLE
MARC 260 and 264 are converted to the same bf:provisionActivity and bf:provisionActivityStatement

### ISSUE THREAD

**Issue by pkiraly** [lcnetdev/marc2bibframe2#12]
Yesterday Jakob Voß (@nichtich) twitted this (https://twitter.com/nichtich/status/846997110021087232):

"Enabled experimental BIBFRAME 2 export for GVK via unAPI (PICA → MARC → MARCXML → BIBFRAME). Example: http://unapi.gbv.de/?id=gvk:ppn:03240817X&format=bibframe"

I have checked what he did and I found a strange thing, and I thing it is due to the conversation (or the different semancit granularity of MARC and BIBFRAME2:

MARCXML:
```
  <datafield tag="260" ind1="3" ind2=" ">
    <subfield code="a">Hamburg</subfield>
    <subfield code="b">Meissner [u.a.]</subfield>
    <subfield code="c">1867-</subfield>
  </datafield>
  <datafield tag="264" ind1="3" ind2="1">
    <subfield code="a">Hamburg</subfield>
    <subfield code="b">Meissner [u.a.]</subfield>
    <subfield code="c">1867-</subfield>
  </datafield>
```

The translated BIBFRAME2:
```
    <bf:provisionActivity>
      <bf:ProvisionActivity>
        <rdf:type rdf:resource="http://id.loc.gov/ontologies/bibframe/Publication"/>
        <bf:status>
          <bf:Status>
            <rdfs:label xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#">current</rdfs:label>
          </bf:Status>
        </bf:status>
        <bf:place>
          <bf:Place>
            <rdfs:label xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#">Hamburg</rdfs:label>
          </bf:Place>
        </bf:place>
        <bf:agent>
          <bf:Agent>
            <rdfs:label xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#">Meissner [u.a.</rdfs:label>
          </bf:Agent>
        </bf:agent>
        <bf:date>1867-</bf:date>
      </bf:ProvisionActivity>
    </bf:provisionActivity>
    <bf:provisionActivityStatement>Hamburg Meissner [u.a.] 1867-</bf:provisionActivityStatement>
    <bf:provisionActivity>
      <bf:ProvisionActivity>
        <rdf:type rdf:resource="http://id.loc.gov/ontologies/bibframe/Publication"/>
        <bf:status>
          <bf:Status>
            <rdfs:label xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#">current</rdfs:label>
          </bf:Status>
        </bf:status>
        <bf:place>
          <bf:Place>
            <rdfs:label xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#">Hamburg</rdfs:label>
          </bf:Place>
        </bf:place>
        <bf:agent>
          <bf:Agent>
            <rdfs:label xmlns:rdfs="http://www.w3.org/2000/01/rdf-schema#">Meissner [u.a.</rdfs:label>
          </bf:Agent>
        </bf:agent>
        <bf:date>1867-</bf:date>
      </bf:ProvisionActivity>
    </bf:provisionActivity>
    <bf:provisionActivityStatement>Hamburg Meissner [u.a.] 1867-</bf:provisionActivityStatement>
```
As you can see there are two identical bf:provisionActivity and bf:provisionActivityStatement elements. In MARC 260 and 264 are quite close to each other semantically, but they are not identical.

BIBFRAME's provisionActivity (http://id.loc.gov/ontologies/bibframe.html#p_provisionActivity): 

Place, name, and/or date information relating to the publication, printing, distribution, issue, release, production, etc. of a resource.

MARC 260 (http://www.loc.gov/marc/bibliographic/bd260.html):

Information relating to the publication, printing, distribution, issue, release, or production of a work. 
Information in field 260 is similar to information in field 264 (Production, Publication, Distribution, Manufacture, and Copyright Notice). Field 260 is useful for cases where the content standard or institutional policies used do not make a distinction between functions.

MARC 264 (http://www.loc.gov/marc/bibliographic/bd264.html):

Statement relating to the publication, printing, distribution, issue, release, or production of a work.
Information in field 264 is similar to information in field 260 (Publication, Distribution, etc. (Imprint)). Field 264 is useful for cases where the content standard or institutional policies make a distinction between functions.

BIBFRAME's ProvisionActivity class has four subtypes: Distribution, Manufacture, Publication, Production. My own conclusion is that it would be nice if the transformation script might have a parameter, with which the client would map whether 260 and 264 should be mapped to the general ProvisionActivity or one of the specific subtypes. That way the distinct information could be reserved. Regarding the provisionActivityStatement, since it is a literal, maybe a prefix or postfix governing parameter would work (which would create something like that "Hamburg Meissner [u.a.] 1867- (publishing)").

**Comment by kirkhess** [comment]
At first glance we thought you prob. shouldn't have a 260 if you have a 264, I'm going to see if LC has any records like this and then we'll decide what we need to do.
I see the point regarding 264 and/or 260 as a parameter, we'll consider that as well. Thanks!

**Comment by jodiw01** [comment]
Won't fix; could impact BIBFRAME to MARC conversion
