### ISSUE TITLE
Instances Type issues in LDR & 006-008

### ISSUE THREAD

**Issue by kirkhess** [lcnetdev/marc2bibframe2#121]
In [xsl/ConvSpec-LDR.xsl,](https://github.com/lcnetdev/marc2bibframe2/blob/master/xsl/ConvSpec-LDR.xsl) the variable on line 116 'workType' uses the LDR/06 and assigns a work type. E.g. for a book it would be 'a' so the type should be Text (aka bf:Text).  It probably would be a good idea to verify every one of the values in the LDR/06 is tested.

Next, the conversion looks at LDR/07 and assigns an issuance and then a possible instanceType. 
e.g. for our book,  LDR/06 is 'a' and the LDR/07 is 'm' the issuance is set to 'mono' and the instanceType should be set to 'Print' (aka bf:Print) This is not part of the specs currently but it is implied in other places that this is happening (you'll note 'if not already set' in some of the specs). What happens is that if a book is not bf:Electronic, it falls out of this and is set to  bf:Instance. Basically, almost every print serial or book is not getting the type bf:Print.

Similarly, serials should have a similar structure and be set in the xsl/ConvSpec-LRD.xsl to bf:Print. I think the other 3 types (Archival, Manuscript and Electronic) are dealt with in other places. bf:Tactile is never used. 

[xsl/ConvSpec-006%2C008.xsl](https://github.com/lcnetdev/marc2bibframe2/blob/master/xsl/ConvSpec-006%2C008.xsl) Line 1021-1028 also assign an instance type, and there's an attempt here to (I think ) default to bf:Print but it instead uses the form in 006/06 for 'r' and assigns bf:Print. There is a very small number of reprints in the LC catalog and these are the only ones which have the type bf:Print. 

In addition, the section in xsl/ConvSpec-006%2C008.xsl which calls templates for the various types there is a table using 006/00 which has a code for the Form of material and this also could be used to set the Instance type.  And I think probably this particular table should be preserved somehow since once you fall into the 008Books section you know you have a book but we don't keep this in the description (this is another issue...)

**Comment by wafschneider** [comment]
@kirkhess -- I think what you're describing is a spec update that we will need to validate with @jodiw01. Is it as simple as adding an `rdf:type bf:Print` property to the main generated `bf:Instance` if LDR/06 = a? Are the `bf:Print` and `bf:Electronic` subclasses mutually exclusive?

**Comment by kirkhess** [comment]
I wanted to keep track of this change - it is in the 1.5 specs.
Yes, that’s basically it. I believe mutually exclusive.
