### ISSUE TITLE
change 655 conversion from madsrdf:GenreForm to bf:GenreForm

### ISSUE THREAD

**Issue by jodiw01** [lcnetdev/marc2bibframe2#165]
Current xslt conversion of MARC tag 655:

https://github.com/lcnetdev/marc2bibframe2/blob/489234bd579beeb3f700af11e0bf16ac8661776e/xsl/ConvSpec-648-662.xsl#L494

<xsl:when test="$pTag='655'">madsrdf:GenreForm</xsl:when>

---
It should be bf:GenreForm to match creation of this class from other MARC tags.

**Comment by wafschneider** [comment]
@jodiw01 -- can you provide a sample record to show both the incorrect and the corrected conversion? The code you cite above sets the class of a component of a `madsrdf:ComplexSubject` from a MARC subfield, so I _think_ the class is correct and consistent in this case (this would be `$a` from the 655 in the context of a `madsrdf:componentList`). The class of the object of the `bf:genreForm` property is correctly set to `bf:GenreForm` in line 61 of the same file.

**Comment by jodiw01** [comment]
Fortunately, this is a non-problem after all.
