### ISSUE TITLE
Wrong bibframe class bf:GrooveCharacteristics in ConvSpec-3xx.xsl

### ISSUE THREAD

**Issue by jiaola** [lcnetdev/marc2bibframe2#20]
In ConvSpec-3XX.xsl, the class bf:GrooveCharacteristics is incorrect. It should be bf:GrooveCharacteristic.

**Comment by wafschneider** [comment]
This is actually a typo in the spec at http://www.loc.gov/bibframe/mtbf/ConvSpec-3XX-R0p.xlsx -- thanks for catching this!
