### ISSUE TITLE
$1 for real world objects are ignored

### ISSUE THREAD

**Issue by gerontakos** [lcnetdev/marc2bibframe2#200]
$1 subfields for real world objects are ignored, at least for 6XX fields. Is there any possibility they could be added to the conversion? They contain useful information, like Wikidata IRIs.

**Comment by wafschneider** [comment]
@gerontakos thanks for the input! It would be valuable to preserve the $1, for sure, but at the moment we don't have a conversion for it (see the [spec](https://github.com/lcnetdev/marc2bibframe2/tree/master/spec) directory in this repository or the official specs as published by the Library at https://www.loc.gov/bibframe/mtbf/).

We have talked about how to model this as distinct from the $0 (which we try to convert into an object URI where possible). There isn't really a great predicate in the BIBFRAME ontology for this purpose. We thought of using the identifiesRWO predicate and RWO class from MADS/RDF, but had some concerns regarding pulling more of that ontology into the conversion (though of course we already use it heavily in the 6XX conversion).

Tagging @jodiw01 for more background as a subject matter expert.

**Comment by jodiw01** [comment]
Conversion of $1 for authorized access points is part of marc2bibframe v2.6
