### ISSUE TITLE
In browser Marc to Bibframe (without a server)

### ISSUE THREAD

**Issue by PhilAndrew** [lcnetdev/marc2bibframe2#206]
Hi there, I wanted to reach out since I am making a simple tool to help convert user inputs about books to Marc records here. [LibraryPhil](https://www.libraryphil.com/). Since all of this works within the browser as a react/typescript webpage, what would be nice is if I could add this marc2bibframe2. Then I could show the same records in bibframe. That would require that I can process the XSLT within the browser.

Do you have any ideas or suggestions on how to go about doing it? Thought I would reach out firstly before attempting to see if you have some idea.

**Comment by kefo** [comment]
I would take a look at [Saxon-JS](https://www.saxonica.com/saxon-js/index.xml).  I've not used it much, and not in the browser, but it should be possible.  

This will help get you started:  https://www.saxonica.com/saxon-js/documentation/index.html#!starting/installing  

NB: you must 'compile' the stylesheet in a specific JSON format.  You can find more information about that here:  https://www.saxonica.com/saxon-js/documentation/index.html#!starting/export

**Comment by PhilAndrew** [comment]
Thanks I got it working at [LibraryPhil](https://www.libraryphil.com/). I made a link at the top, after entering a little book info then click the link View BibFrame 2.0 (on top right side) then it outputs the BibFrame. Not sure if its correct or not, I just hooked it up and I don't know anything at all about BibFrame yet.
