### ISSUE TITLE
Apparent duplication of field rdf:type

### ISSUE THREAD

**Issue by laura-ake** [lcnetdev/marc2bibframe2#218]
Can you please check the code that generates this section of the converted record?  It appears a line is being duplicated, and may be out of place:
[Tidsskrigt for Den norske legeforening MARCXML 2022_01_12.txt](https://github.com/lcnetdev/marc2bibframe2/files/7856538/Tidsskrigt.for.Den.norske.legeforening.MARCXML.2022_01_12.txt)

 </bf:Work>
   <bf:Instance rdf:about="https://open-na.hosted.exlibrisgroup.com/alma/01GALI_EMORY/bf/entity/instance/9937294465602486">
      <rdf:type rdf:resource="http://id.loc.gov/ontologies/bibframe/Print"/>
      <bf:issuance>
         <bf:Issuance rdf:about="http://id.loc.gov/vocabulary/issuance/serl"/>
      </bf:issuance>
      <bf:carrier>
         <bf:Carrier rdf:about="http://id.loc.gov/vocabulary/carriers/cr">
            <rdfs:label>online resource</rdfs:label>
         </bf:Carrier>
      </bf:carrier>
      <rdf:type rdf:resource="http://id.loc.gov/ontologies/bibframe/Electronic"/>
      <rdf:type rdf:resource="http://id.loc.gov/ontologies/bibframe/Electronic"/>
      
      It also appears to my eyes that in addition to the duplicated <rdf:type> elements, there's another <rdf:type> element referring to the same bf:instance with a different value.  This comes from conversion of an electronic journal record (so far, we haven't found an example with a print journal).  I have attached the marcxml record from our Ex Libris Alma catalog and a copy of the latest converted output from Alma (which incorporates marc2bibframe2 in its tools).  We confirmed via a separate installation of marc2bibframe2 that the duplication is happening for this record outside Alma.  
[Tidsskrift for Den norske legeforeningThe Journal of the Norwegian Medical Association.bibframexml_2022_01_12.txt](https://github.com/lcnetdev/marc2bibframe2/files/7856457/Tidsskrift.for.Den.norske.legeforeningThe.Journal.of.the.Norwegian.Medical.Association.bibframexml_2022_01_12.txt)

Thank you.  Laura Akerman for the IGELU-ELUNA Linked Open Data Community of Practice Working Group

**Comment by wafschneider** [comment]
@laura-ake thank you for this feedback, I apologize for the long delay in getting back to you.

The first `rdf:type` property on the bf:Instance comes from the leader. The MARC to BIBFRAME [specification|https://www.loc.gov/bibframe/mtbf/index.html] state that if LDR/07 is "s" and LDR/06 is "a", a triple of Instance - rdf:type - bf:Print should be created.

The second and third rdf:type properties are coming from the two 007 fields in the record:
```
<controlfield tag="007">cr-bn||||||abp</controlfield>
<controlfield tag="007">cr-bn||||||ada</controlfield>
```

It looks like this is an error in the converter, probably left over from a previous version of the specifications, as the current specs do not have this direction, instead specifying that `bf:media` and `bf:carrier` properties be created if they are not already created by a 337 or 338. The implementation looks incorrect to me.

@jodiw01 -- if you can confirm my understanding I can fix this issue. Sorry for the inconvenience!

**Comment by laura-ake** [comment]
Thanks Wayne.  Let me know if I can help with testing a fix, if I can remember what our example was when that happens.

Laura

From: Wayne Schneider ***@***.***>
Sent: Thursday, April 28, 2022 12:23 AM
To: lcnetdev/marc2bibframe2 ***@***.***>
Cc: Akerman, Laura ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [lcnetdev/marc2bibframe2] Apparent duplication of field rdf:type (Issue #218)


@laura-ake<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flaura-ake&data=05%7C01%7Cliblna%40emory.edu%7Cf3e39c994fee4c003c0e08da28cec591%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637867165790087704%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2BxY0fSFwq41D1Mui14IT9vi3aEQfGuAZ1q%2BPkTvD0Kg%3D&reserved=0> thank you for this feedback, I apologize for the long delay in getting back to you.

The first rdf:type property on the bf:Instance comes from the leader. The MARC to BIBFRAME [specification|https://www.loc.gov/bibframe/mtbf/index.html] state that if LDR/07 is "s" and LDR/06 is "a", a triple of Instance - rdf:type - bf:Print should be created.

The second and third rdf:type properties are coming from the two 007 fields in the record:

<controlfield tag="007">cr-bn||||||abp</controlfield>

<controlfield tag="007">cr-bn||||||ada</controlfield>

It looks like this is an error in the converter, probably left over from a previous version of the specifications, as the current specs do not have this direction, instead specifying that bf:media and bf:carrier properties be created if they are not already created by a 337 or 338. The implementation looks incorrect to me.

@jodiw01<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjodiw01&data=05%7C01%7Cliblna%40emory.edu%7Cf3e39c994fee4c003c0e08da28cec591%7Ce004fb9cb0a4424fbcd0322606d5df38%7C0%7C0%7C637867165790087704%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=PtuptDyZTdoR1%2BJvOt2m8KQ%2Frw37mGI%2FzUkHH2G3QhY%3D&reserved=0> -- if you can confirm my understanding I can fix this issue. Sorry for the inconvenience!

-
