### ISSUE TITLE
Add three spaces as an option to not create bf:duration (tag 008)

### ISSUE THREAD

**Issue by ivozandhuis** [lcnetdev/marc2bibframe2#228]
https://github.com/lcnetdev/marc2bibframe2/blob/a2c5a96e0286c45bfd441bd493d31a0f5b86904a/xsl/ConvSpec-006%2C008.xsl#L497

These lines determine whether bf:duration is generated or not. This is detected by finding the character '|||' or 'nnn' from character 19 on wards in tag 008. Should three spaces be handled the same way? Than add an extra line:
`<xsl:when test="substring($dataElements,1,3) = '   '"/>`

**Comment by jodiw01** [comment]
This issue has been fixed
