### ISSUE TITLE
Art Reproduction code is arr not art

### ISSUE THREAD

**Issue by kirkhess** [lcnetdev/marc2bibframe2#229]
See https://github.com/lcnetdev/marc2bibframe2/blob/a2c5a96e0286c45bfd441bd493d31a0f5b86904a/xsl/conf/codeMaps.xml#L380

http://id.loc.gov/vocabulary/marcgt/art = Article

It should be changed to:
http://id.loc.gov/vocabulary/marcgt/arr = Art Reproduction

**Comment by jodiw01** [comment]
Thank you; the specs have been corrected.
