### ISSUE TITLE
bflc:SecondaryInstance mentioned, but does not exist in bflc documentation (2.2.0) at https://id.loc.gov/ontologies/bflc.html (should probably go to bflc 2.3.0?)

### ISSUE THREAD

**Issue by schlawiner** [lcnetdev/marc2bibframe2#230]
bflc:SecondaryInstance is mentioned as being used for splitting instances, both in the [2.4.0 release notes](https://github.com/lcnetdev/marc2bibframe2/releases/tag/v.2.4.0) as well as, of course, in the code itself. But the web view of the current bflc version (marked as 2.2.0) documents no such class, see class list at https://id.loc.gov/ontologies/bflc.html. 

https://id.loc.gov/ontologies/bflc/SecondaryInstance.rdf does exist, however.

There are some more small things amiss on https://id.loc.gov/ontologies/bflc.html - the Namespace: http://id.loc.gov/ontologies/bflc/ link at the top gives we a 404/not found, and clicking the "Version IRI" http://id.loc.gov/ontologies/bflc-2-2-0/ gives me a red "Legacy Ontology Documentation" notice box above the content.

Trying, on a guess, https://id.loc.gov/ontologies/bflc-2-3-0.html (which doesn't seem to be linked anywhere?) does give me a page where SecondaryInstance is documented. So this should probably marked as the current version to be linked to for https://id.loc.gov/ontologies/bflc.html

**Comment by ntra00** [comment]
Thanks for this. I wonder if your first issue was a caching one? SecondaryInstance is at https://id.loc.gov/ontologies/bflc.html for me. We will correct the redirect for bflc/ so that it resolves to https://id.loc.gov/ontologies/bflc, which is the same as bflc-2-3-0. (Version 2-2-0 is therefore "legacy".)

**Comment by kefo** [comment]
Hi @schlawiner - can I ask you to check all of your issues and they look good, please go ahead and close this issue.
