### ISSUE TITLE
ProvisionActivity: add support for 26x ind1 to/from MARC and ordering ProvisionActivity resources

### ISSUE THREAD

**Issue by kirkhess** [lcnetdev/marc2bibframe2#234]
The instructions on how to use the 264 for PCC/RDA records were published by LC in 2012:
[http://www.loc.gov/aba/pcc/documents/264-Guidelines.doc](http://www.loc.gov/aba/pcc/documents/264-Guidelines.doc)

See also [https://www.oclc.org/bibformats/en/2xx/264.html](https://www.oclc.org/bibformats/en/2xx/264.html)

In BIBFRAME 2.3, there's no support for the 26x ind1. I think perhaps this is a value judgement about the utility of this indicator. That might be something you need to bring to the PCC to have them decide if that indicator is no longer useful and/or add ind1 support in provision activity resources. 

The CCM 10.5.2 mentions using an appropriate 1st indicator with a use case. The CEG appendix E has instructions for 260 pp. 7-8. 

In BIBFRAME 2.3, there's no way to indicate the order of ProvisionActivity resources. I suppose you could force it to happen with some kind of sorting process.
"Order of 264 fields: Give the fields for each function of entity statement recorded (second indicator value) together and in chronological order from earliest to latest (ordered by first indicator value). Record Copyright Notice Date as the last field."

**Comment by kefo** [comment]
Again, we think this is more a conversoin issue presently, though the ordering may or may not be.  (But that is a *separate* issue than the indicator one.)

**Comment by jodiw01** [comment]
chart of different configurations of 26X fields, and the marc2bibframe conversion path:

![image](https://github.com/lcnetdev/marc2bibframe2/assets/8515603/d6a6c254-f7b2-433d-addd-4776cdbd7f0d)

**Comment by jodiw01** [comment]
Included in marc2bibframe v2.5
