### ISSUE TITLE
Create bf:translationOf relationships from 240 field

### ISSUE THREAD

**Issue by osma** [lcnetdev/marc2bibframe2#25]
I originally [posted this](https://listserv.loc.gov/cgi-bin/wa?A1=ind1703&L=bibframe#3) to the BIBFRAME mailing list, but the discussion died down quickly.

This converter seems to create bf:translationOf relationships only from MARC field 765. The older marc2bibframe converter could generate them from 240 fields as well. So for a record like this ([full record here](https://gist.github.com/osma/d9ec86bf73eefa038c36df48cb01b7b1)):

```
0411  L $$afin$$heng
1001  L $$aHawking, Stephen.
24012 L $$aA brief history of time,$$lsuomi
24510 L $$aAjan lyhyt historia /$$cStephen Hawking ; piirrokset: Ron Miller ; suomentanut Risto Varteva.
```

...it would generate two Works, one for the original work ("A brief history of time") and one for the translation ("Ajan lyhyt historia"), with a `bf:translationOf` relationship in between these entities.

This record is not special in any way - we have more than 100k records in the Fennica database alone following this pattern (original work title in 240) and many more in the Melinda union catalog. We only have very few 765 links in our records.

Putting the original of the translation in the 240 field is in my understanding (although I'm not a cataloger!) pretty common practice. See for example [this guide](https://library.osu.edu/blogs/cdad/2008/05/06/how-to-catalog-a-translation/) from Ohio State University library.

It's no problem for me to copy the information from 240 to 765 as a preprocessing step - in fact I've already implemented that using a Catmandu Fix [script](https://github.com/NatLibFi/bib-rdf-pipeline/blob/use-marc2bibframe2/scripts/preprocess-marc.fix#L37). But not using 240 to create a Work representing the original of the translation felt like a missing feature in the converter, particularly since the old converter could do that.

**Comment by kirkhess** [comment]
Sorry we forgot about this, thanks for the record, Wayne and I will check on this w/ a xspec test.

**Comment by kirkhess** [comment]
http://id.loc.gov/tools/bibframe/compare-lccn/full-ttl?find=2015298246

**Comment by wafschneider** [comment]
This is implemented in branch https://github.com/lcnetdev/marc2bibframe2/tree/rc-1.2 -- hopefully to release this week.
