### ISSUE TITLE
Processing error in v2.8

### ISSUE THREAD

**Issue by kouralex** [lcnetdev/marc2bibframe2#253]
When testing the new v2.8 version, I encountered an XPath error whilst running the main `marc2bibframe.xsl` for one our MARCXML file:  
[000900729.txt](https://github.com/user-attachments/files/17900977/000900729.txt)
 

Short stack trace:
```xsltIf: test count($pRelated880s) > 0
Lookup variable 'pRelated880s'
XPath error : Invalid type
xsltIf: test evaluate to -1
```

Additional info: the file can be converted using v2.7.

**Comment by kefo** [comment]
What XSLT processor are you using?

**Comment by kefo** [comment]
Also, can you provide the actual command and any parameters.  I have been unable to reproduce this with the sample record (thank you, btw!) with saxon or xsltproc.

**Comment by kefo** [comment]
OK.  I dug deeper and I think I saw the issue (in xsltproc) and it has been addressed.  Can you grab this branch and give it a quick test, please:  https://github.com/lcnetdev/marc2bibframe2/tree/v2.8.1-dev

**Comment by kefo** [comment]
No worries.  Hope this gets the job done.
