### ISSUE TITLE
bflc:indexedIn property doesn't exist in bflc ontology

### ISSUE THREAD

**Issue by jiaola** [lcnetdev/marc2bibframe2#26]
In ConvSpec-490-510-530to535-Links.xsl, the template   <xsl:template match="marc:datafield[@tag='510' or @tag='880']" mode="instance510">, it creates a property bflc:indexedIn. However, that property doesn't exist in bflc. Should it be something else?

**Comment by kirkhess** [comment]
Good catch - we'll add it to the list.

**Comment by kirkhess** [comment]
Do you have an example of a 510 we can check? Commenting w/a LCCN or a link should be easy. Thanks!

**Comment by jiaola** [comment]
@kirkhess The xspec has some examples already.

**Comment by kirkhess** [comment]
Those are only unit tests, I meant a real record with a 510 I can test in metaproxy/yaz.

**Comment by jiaola** [comment]
I found a few in the datasets I am playing with but the 510 notes are not found in LOC catalog. 

Here's an example attached (It's marcxml but I had to rename it to txt to attach it)
[510.txt](https://github.com/lcnetdev/marc2bibframe2/files/994076/510.txt)

**Comment by jiaola** [comment]
And just curious, how is metaproxy/yaz being used in your workflow of converting MARC at LoC?

**Comment by kirkhess** [comment]
We're using:
yaz-record-conv {active config file} {marcxml converted from MARC21 by yaz}

**Comment by kirkhess** [comment]
Transformed version. `

[510.rdf.txt](https://github.com/lcnetdev/marc2bibframe2/files/996877/510.rdf.txt)

`

**Comment by wafschneider** [comment]
According to the maintainers of the bflc ontology and the MARC to BIBFRAME conversion spec, bflc:indexedIn is correct. An update to the ontology will be coming out to cover the existing conversion.
