### ISSUE TITLE
Update series conversion

### ISSUE THREAD

**Issue by wafschneider** [lcnetdev/marc2bibframe2#27]
Implement updated ConvSpec for 240+, 490+ and Process 6

**Comment by kirkhess** [comment]
Missing Conversion of 49X $3: http://id.loc.gov/tools/bibframe/compare-lccn/full-ttl?find=79640364

**Comment by kirkhess** [comment]
Associate ISSN from 49X $x with 830 in conversion: http://id.loc.gov/tools/bibframe/compare-lccn/full-ttl?find=94067679

**Comment by wafschneider** [comment]
Sent to Sally:

> A few clarifying questions:
> 
> The spec for 490 says to ignore the first indicator (regarding series tracing). The MARC standards suggest that if ind 1 = 0, there will be no 8XX to pair with. If ind 1 = 0, should we still try to pair with an 8XX?
> 
> Does each 490 pair with an 8XX, or is it each 490 $a($x)($v)?
> 
> Related question - it appears that repeating the $a/$x/$v has 2 use cases -- one for a subseries, one for a parallel title. For a parallel title, does a single 490 get broken up into multiple hasSeries properties?
> If there is no 8XX to pair with a 490, do we still create the instanceOf property and Work object?
> 
> If there is no 490 to pair with an 8XX, do we still create the Instance object of the hasSeries property, or do we just let the hasSeries property take the Work created by the 8XX as its object?

**Comment by wafschneider** [comment]
The conversion has been updated in branch issue-27. A development version of the conversion is installed on mprxyvls02. 

URLs for the acceptance test records:
http://mprxyvls02.loc.gov:210/LCDB?version=1.1&operation=searchRetrieve&query=rec.id%3D11225612&recordSchema=bibframe2-dev&startRecord=1&maximumRecords=1

http://mprxyvls02.loc.gov:210/LCDB?version=1.1&operation=searchRetrieve&query=rec.id%3D2071829&recordSchema=bibframe2-dev&startRecord=1&maximumRecords=1

**Comment by wafschneider** [comment]
I've cleaned up the code and updated the development server with the latest code for testing.
