### ISSUE TITLE
Cannot convert uniform titles

### ISSUE THREAD

**Issue by amberbilley** [lcnetdev/marc2bibframe2#29]
Trying to find a conversation example with uniform titles, (LCCN 2001202342 for example). I have tried several records without success. When I try to convert a record with a uniform title, the resulting serialization says: 

"BIBFRAME (Turtle) NameTitle to Works Transform

(source: 

Is this a bug?

**Comment by kirkhess** [comment]
It's a bug in the Compare tool - we're working on it.

-Kirk

**Comment by ntra00** [comment]
found and fixed. sorry; nate

**Comment by amberbilley** [comment]
Great! Thank you for the quick response and fix!!!
