### ISSUE TITLE
HierarchicalGeographic change

### ISSUE THREAD

**Issue by jodiw01** [lcnetdev/marc2bibframe2#30]
Change to conversion of MARC tag 662

Old:
662 - SUBJECT ADDED ENTRY--HIERARCHICAL PLACE NAME (R)	## - bf:subject - bf:Place - madsrdf:HierarchicalGeographic  rdfs:label "content of $abcdfgh separated by "--""
   Subfield Codes	 
      $a - madsrdf:Country or larger entity (R)	## - madsrdf:Country  rdfs:label "content of $a"
      $b - First-order political jurisdiction (NR)	## - madsrdf:County  rdfs:label "content of $b"
      $c - Intermediate political jurisdiction (R)	## - madsrdf:State  rdfs:label "content of $c"

New:
662 - SUBJECT ADDED ENTRY--HIERARCHICAL PLACE NAME (R)	## - bf:subject - bf:Place - madsrdf:HierarchicalGeographic  rdfs:label "content of $abcdfgh separated by "--""
   Subfield Codes	 
      $a - madsrdf:Country or larger entity (R)	## - madsrdf:Country  rdfs:label "content of $a"
      $b - First-order political jurisdiction (NR)	## - **madsrdf:State  rdfs:label "content of $b"**
      $c - Intermediate political jurisdiction (R)	## - **madsrdf:County  rdfs:label "content of $c"**

**Comment by kirkhess** [comment]
Acceptance test: http://id.loc.gov/tools/bibframe/compare-lccn/full-ttl?find=2015633199

**Comment by wafschneider** [comment]
The same change needs to be made to the conversion for the 752
