### ISSUE TITLE
conversion of variantType data in MARC tag 246

### ISSUE THREAD

**Issue by jodiw01** [lcnetdev/marc2bibframe2#41]
In the spec, the data in MARC tag 246 $i is mapped to variantType - "content of $i" but I do not see this field in any of the converted records.

Example
http://mprxyvls02.loc.gov:210/LCDB?version=1.1&operation=searchRetrieve&query=rec.id%3D14658976&recordSchema=bibframe2-dev&startRecord=1&maximumRecords=1

This record has five occurrences of MARC tag 246 $i and none appear in the conversion.

**Comment by wafschneider** [comment]
After review, it looks like this issue needs a change to the conversion specifications (in progress) to handle $i differently.

**Comment by wafschneider** [comment]
I've installed the updated conversion on mprxyvls02. I think it looks pretty good:
http://mprxyvls02.loc.gov:210/LCDB_MARC8?version=1.1&operation=searchRetrieve&query=rec.id%3D14658976&recordSchema=bibframe2-dev&startRecord=1&maximumRecords=1
