### ISSUE TITLE
Conversion error with 240 and 880 fields

### ISSUE THREAD

**Issue by osma** [lcnetdev/marc2bibframe2#49]
I tried to convert [this record](https://gist.github.com/osma/9495f0eb638119115c64fb40af1e43e5) and got this error:

```
runtime error: file ../marc2bibframe2/xsl/ConvSpec-240andX30-UnifTitle.xsl line 415 element attribute
xsl:attribute: Cannot add attributes to an element if children have been already added to the element.
```

The error seems to be related to the 240 field (which contains a transliterated original title) and the 880 field, which contains the original Cyrillic title.

According to our catalogers the record is using 240 and 880 fields correctly, so it seems like a bug in the converter.

**Comment by osma** [comment]
I'm using v1.2.0

**Comment by wafschneider** [comment]
The issue was an attempt to create an xml:lang attribute at the wrong point in the template. Pull request #50 in progress. @kirkhess -- I will also make release 1.2.2, so the fix can be included in the update to lx2.loc.gov next week.

**Comment by osma** [comment]
Thanks again @wafschneider !
