### ISSUE TITLE
Field 382 subfield 2

### ISSUE THREAD

**Issue by kiegel** [lcnetdev/marc2bibframe2#62]
Field 382 (Medium of performance) has subfield 2 for Source of term.  The converter adds bf:source for terms from subfields a, b, d and p.  However, the MARC format says subfield 2 applies only to subfield a.  We agree that source should be present for all four subfields but if you want to be in conformance with MARC practice you will eliminate it for terms from subfields b, d, and p.

Examples from a test record:

Correct

	[ a bf:MusicMedium ;
            rdfs:label "382 Medium of performance subfield a" ;
            bf:count "382 e",
                "382 n" ;
            bf:source [ a bf:Source ;
                    rdfs:label "382subfield2" ] ],

Incorrect according to MARC standards

	[ a bf:MusicMedium ;
            rdfs:label "382 b" ;
            bf:count "382 n" ;
            bf:source [ a bf:Source ;
                    rdfs:label "382subfield2" ] ],

	[ a bf:MusicMedium ;
            rdfs:label "382 d" ;
            bf:count "382 n" ;
            bf:source [ a bf:Source ;
                    rdfs:label "382subfield2" ] ;
            bf:status [ a bf:Status ;
                    rdfs:label "doubling" ] ],

	[ a bf:MusicMedium ;
            rdfs:label "382 p" ;
            bf:count "382 e",
                "382 n" ;
            bf:source [ a bf:Source ;
                    rdfs:label "382subfield2" ] ;
            bf:status [ a bf:Status ;
                    rdfs:label "alternative" ] ],

**Comment by kiegel** [comment]
Good news.  The MARC standard is being updated to include subfields b, d and p.  So the converter is operating in conformance with the standard.

$2 - Source of term
MARC code that identifies the source of the term in subfield $a, $b, $d, and/or $p when it is from a controlled list.

This is a minor editorial change.  The revised definition will accompany the next MARC update, which will be published soon.

**Comment by kirkhess** [comment]
Thanks - Wayne will work on verifying the $2 issue.

**Comment by wafschneider** [comment]
The MARC update has been published. The converter is in compliance, as @kiegel notes above.
