### ISSUE TITLE
Field 382 subfields d and p

### ISSUE THREAD

**Issue by kiegel** [lcnetdev/marc2bibframe2#65]
_[Posted here from the BIBFRAME list so the record has all of our comments on this field]_

Field 382 (Medium of performance) has subfield d for Doubling instrument and subfield p for Alternative medium of performance.  The LC converter puts each of them in separate blank nodes and uses bf:status to record the fact that the medium is doubling or alternative.

Examples from a test record:

	bf:musicMedium [ a bf:MusicMedium ;
            rdfs:label "382 d" ;
            bflc:appliesTo [ a bflc:AppliesTo ;
                    rdfs:label "382 3" ] ;
            bf:count "382 n" ;
            bf:source [ a bf:Source ;
                    rdfs:label "382subfield2" ] ;
            bf:status [ a bf:Status ;
                    rdfs:label "doubling" ] ] .

	bf:musicMedium [ a bf:MusicMedium ;
            rdfs:label "382 p" ;
            bflc:appliesTo [ a bflc:AppliesTo ;
                    rdfs:label "382 3" ] ;
            bf:count "382 e",
                "382 n" ;
            bf:source [ a bf:Source ;
                    rdfs:label "382subfield2" ] ;
            bf:status [ a bf:Status ;
                    rdfs:label "alternative" ] ] .

However, the relationship of terms in subfields d and p is positional, that is, the doubling or alternative medium refers to a previous subfield a or b (or d in the case of subfield p).  To take an example, 

382 01 $a violin $n 1 $p flute $n 1 $a cello $n 1 $a piano $n 1 $s 3 $2 lcmpt

the flute is an alternative for the violin rather than for the cello or piano.  

The present conversion does not provide enough information.  It is not enough to say that the flute is an alternative medium, but it must also be specified what it is an alternative for.

A new data structure may be needed.  We think it would be best to incorporate doubling and alternative terms into the blank node of the terms to which they apply in some manner.  Alternately, the current structure can be used to make the relationship between the terms more clear, e.g. by including more information in bf:status, such as “alternative for violin”.  For example:

	bf:musicMedium [ a bf:MusicMedium ;
            rdfs:label "violin" ;
            bf:count "1" ;
            bf:source [ a bf:Source ;
                    rdfs:label "lcmpt" ]],

	 [ a bf:MusicMedium ;
            rdfs:label "flute" ;
            bf:count "1" ;
            bf:status [ a bf:Status ;
                    rdfs:label "alternative for violin" ] ] .

**Comment by jodiw01** [comment]
should use existing bf:instrumentalType instead

**Comment by jodiw01** [comment]
The specs have been revised to change the wording, and to use bf:instrumentalType. Further adjustments may occur in the future if the PMO terms are used.
