### ISSUE TITLE
Labels for fixed field codes

### ISSUE THREAD

**Issue by kiegel** [lcnetdev/marc2bibframe2#68]
In some cases, MARC fixed-field codes are placed in bf:code, e.g.:

```
bflc:encodingLevel [ a bflc:EncodingLevel ;
               bf:code "f" ] .

bf:status [ a bf:Status ;
               bf:code "c" ] .
```
This practice preserves the inscrutability of MARC.  These codes have corresponding labels, and it would be better to use both, e.g.

```
bflc:encodingLevel [ a bflc:EncodingLevel ;
	       rdfs:label "full level" ;
               bf:code "f" ] .

bf:status [ a bf:Status ;
	       rdfs:label "corrected or revised" ;
               bf:code "c" ] .
```
You already use both a label and a code in some instances:

```
bf:notation [ a bf:Script ;
            rdfs:label "extended roman" ;
            bf:code "b" ] .
```
A review of the conversion of fixed field codes in order to find cases when an additional label is needed would be a good thing.

**Comment by kirkhess** [comment]
This is already in progress - these codes are being converted to lists and uploaded to id.loc.gov - e.g http://id.loc.gov/vocabulary/menclvl/f is the uri for your first example.

Once we get the code list updated we're updating the conversion specifications and finally the conversion. This should be completed relatively soon. Thanks for your comments!
