### ISSUE TITLE
MARC subfield $1 for Real World Objects in VIAF

### ISSUE THREAD

**Issue by elephantsmith** [lcnetdev/marc2bibframe2#69]
MARCEdit already started to designate MARC subfield $1 for Real World Objects from VIAF.    Examples can be found in the following 700 fields:
=700  1\$aSamuelson, Marc,$d1961-$efilm producer.$0http://id.loc.gov/authorities/names/no2001042003$1http://viaf.org/viaf/34105656
=700  1\$aSamuelson, Peter,$d1951-$efilm producer.$0http://id.loc.gov/authorities/names/no2001042004$1http://viaf.org/viaf/26712622

The conversion specs and converter need to be updated to convert MARC subfield $1 to BIBFRAME if it exists in a MARC record as the following examples:
Example 1:
 <bf:contribution>
         <bf:Contribution>
            <bf:agent>
               <bf:Agent rdf:about="http://id.loc.gov/authorities/names/no2001042003">
                  <rdf:type rdf:resource="http://id.loc.gov/ontologies/bibframe/Person"/>
                  <bflc:name00MatchKey>Samuelson, Marc, 1961-</bflc:name00MatchKey>
                  <bflc:name00MarcKey>7001 $aSamuelson, Marc,$d1961-$efilm producer.$0http://id.loc.gov/authorities/names/no2001042003$1http://viaf.org/viaf/34105656</bflc:name00MarcKey>
                  <rdfs:label>Samuelson, Marc, 1961-</rdfs:label>
                  <bf:identifiedBy>
                     <bf:Identifier>
                        <rdf:value rdf:resource="http://viaf.org/viaf/34105656"/>
                     </bf:Identifier>
                  </bf:identifiedBy>
               </bf:Agent>
            </bf:agent>
            <bf:role>
               <bf:Role>
                  <rdfs:label>film producer.</rdfs:label>
                  <bflc:relatorMatchKey>film producer</bflc:relatorMatchKey>
               </bf:Role>
            </bf:role>
         </bf:Contribution>
      </bf:contribution>
Example 2:
   <bf:contribution>
         <bf:Contribution>
            <bf:agent>
               <bf:Agent rdf:about="http://id.loc.gov/authorities/names/no2001042004">
                  <rdf:type rdf:resource="http://id.loc.gov/ontologies/bibframe/Person"/>
                  <bflc:name00MatchKey>Samuelson, Peter, 1951-</bflc:name00MatchKey>
                  <bflc:name00MarcKey>7001 $aSamuelson, Peter,$d1951-$efilm producer.$0http://id.loc.gov/authorities/names/no2001042004$1http://viaf.org/viaf/26712622</bflc:name00MarcKey>
                  <rdfs:label>Samuelson, Peter, 1951-</rdfs:label>
                  <bf:identifiedBy>
                     <bf:Identifier>
                        <rdf:value rdf:resource="http://viaf.org/viaf/26712622"/>
                     </bf:Identifier>
                  </bf:identifiedBy>
               </bf:Agent>
            </bf:agent>
            <bf:role>
               <bf:Role>
                  <rdfs:label>film producer.</rdfs:label>
                  <bflc:relatorMatchKey>film producer</bflc:relatorMatchKey>
               </bf:Role>
            </bf:role>
         </bf:Contribution>
      </bf:contribution>

**Comment by jodiw01** [comment]
The conversion specifications have been updated.
