### ISSUE TITLE
Obsolete codes in field 048

### ISSUE THREAD

**Issue by kiegel** [lcnetdev/marc2bibframe2#73]
Field 048 (Number of Musical Instruments or Voices Code) contains MARC instruments and voices codes, e.g. "ba" for "Horn".  Obsolete and unspecified codes, which are still present in legacy records, cause transformation failures.  Stylesheet ConvSpec-010-048.xml fails on line 753 with error code XTDE0820.

Here are examples from live records.

OCLC #6075808
048	__ |a wa01 |a sb01 |a vz01 |a ta01
vz is obsolete

OCLC #37290943
048 __ |b vn01 |a tb01 |a ka01 |a ea01 |a zn01
zn is unspecified

OCLC #6055856
048	__ |b vd01 |a wa01 |a wb01 |a ka01 |a po01 |a sa01 |a sb01 |a sc01 |a sd01 
po is obsolete

Please include all codes listed in OCLC Bib Formats:  https://www.oclc.org/bibformats/en/0xx/048.html 

Error checking to catch table-lookup failures would be helpful too.  When doing batch conversion of large numbers of records, a problem in a single score record can abort the entire batch.

**Comment by kiegel** [comment]
Here is a list of the codes that are missing and a suggested value for the appropriate instrumentType/ensembleType/voiceType.  There is no label for these codes.

bo - brass
cz - chorus
eo - electronic
ko - keyboard
oo - instrumental
po - percussion
so - string, bowed
to - string, plucked
vz - voice
wo - woodwind
zn - unspecified
zu - unknown
zz - unspecified

For codes zn, zu, and zz, instrumentType is probably the best choice for the property.  An alternative for these codes is to suppress output, since they do not provide much information.

**Comment by jodiw01** [comment]
spec updated
