### ISSUE TITLE
ISSNs contain extra punctuation

### ISSUE THREAD

**Issue by osma** [lcnetdev/marc2bibframe2#8]
I noticed a minor issue when converting records containing ISSNs. For example, the second record from [this batch of two records](https://gist.github.com/osma/8fa1dc7c05cc53927722353f72a3e273) has a `490` field containing an ISSN:

```xml
    <marc:datafield tag="490" ind1="1" ind2=" ">
      <marc:subfield code="a">Jyväskylä studies in humanities,</marc:subfield>
      <marc:subfield code="x">1459-4323 ;</marc:subfield>
      <marc:subfield code="v">187</marc:subfield>
    </marc:datafield>
```

The ISSN gets converted into this BIBFRAME2 RDF/XML:
```xml
        <bf:identifiedBy>
          <bf:Issn>
            <rdf:value>1459-4323 ;</rdf:value>
          </bf:Issn>
        </bf:identifiedBy>
```

Notice that the `rdf:value` still contains the space and semicolon. I would expect these to be stripped as they are not really part of the ISSN code.

**Comment by kirkhess** [comment]
We will address this in our next update. Thanks!
