### ISSUE TITLE
859 not converted

### ISSUE THREAD

**Issue by kirkhess** [lcnetdev/marc2bibframe2#80]
LC uses 859 as a alternative to 856 to avoid creating conflicts with 856 data sent to OCLC. However, 859 is not mentioned in Process 3, and therefore is not converted. It is equivalent to 856 so it needs to be added to ConvSpec-841-887 as an OR condition.

**Comment by wafschneider** [comment]
This is resolved with commit https://github.com/lcnetdev/marc2bibframe2/commit/175f26e0af39ba2fb76bd8991714057ae2d0e5b0, in the soon-to-be-released v1.4.0 branch.
