### ISSUE TITLE
Don't create bflc:relatorMatchKey property

### ISSUE THREAD

**Issue by wafschneider** [lcnetdev/marc2bibframe2#81]
This property was created to work around issues with the LC label lookup service and trailing punctuation, it is no longer needed.

**Comment by wafschneider** [comment]
This will also require some tweaking of the sample yaz record conversion configuration.

**Comment by wafschneider** [comment]
In my testing, the label service for relators still fails if there is trailing punctuation:

http://id.loc.gov/vocabulary/relators/label/illustrator -- results in "302 FOUND" with header `Location : http://id.loc.gov/vocabulary/relators/ill`

http://id.loc.gov/vocabulary/relators/label/illustrator. -- results in "404 Not Found"

@ntra00 -- am I missing something?

**Comment by ntra00** [comment]
I think we’ve been adding the chop-punctuation on a piecemeal basis to our label service. Maybe we should just add it more broadly to any label lookups. We’ll discuss internally and address this. We definitely would need to have it for any lookups we put into the record-conv.xml file.

**Comment by ntra00** [comment]
wayne, the label service covers relators (now). http://id.loc.gov/vocabulary/relators/label/illustrator.
