### ISSUE TITLE
Fix Empty Cartographic elements

### ISSUE THREAD

**Issue by kirkhess** [lcnetdev/marc2bibframe2#83]
Example:
http://id.loc.gov/tools/bibframe/compare-id/full-rdf?find=5532485

The scales are created for 034/255 but there is an empty bf:cartographicAttributes/bf:Cartographic when there is just a 255$a or 034$abc w/o 255$b-g or 034$defg.

The specs for 255 don't specify when there is only a 255$a but it is pretty clear in 034. Do we need to change it to look more like the 010-048 spec for 034 where there's a column for W-scale-Scale and another for W-cartographicAttributes-Cartographic?

**Comment by wafschneider** [comment]
Another sample record: http://lx2.loc.gov:210/LCDB?query=rec.id=14870021&recordSchema=bibframe2&maximumRecords=1

**Comment by wafschneider** [comment]
Related conversion spec: [ConvSpec-250-270-v1.4.xlsx](https://github.com/lcnetdev/marc2bibframe2/files/2861955/ConvSpec-250-270-v1.4.xlsx)

**Comment by wafschneider** [comment]
Fixed in branch v1.4.0
