### ISSUE TITLE
Wrong instructions for running test suite

### ISSUE THREAD

**Issue by osma** [lcnetdev/marc2bibframe2#9]
I tried to run the XSpec test suite. First I installed XSpec and its dependencies (I'm running Ubuntu Linux 16.04). Then I ran the command that was specified in the top level README:

>Once you have XSpec installed, you can run the entire test suite with the command (for Mac OS or >Linux):
>
>xspec.sh test/marc2bibframe.xspec

But this fails because there is no file called `test/marc2bibframe.xspec`. There are 17 individual xspec files but no master file that would run all tests.

Looking at `.travis.yml` it runs each test file individually.

I think there should be a single command that runs the full test suite, as hinted in the README. I can do it with a `for` loop, but that's hardly optimal: `for i in test/*.xspec; do xspec.sh $i; done`

**Comment by kirkhess** [comment]
We'll update the documentation with working instructions.

**Comment by wafschneider** [comment]
There were 2 issues:
1. We accidentally deleted the marc2bibframe2.xspec file from the test directory (now restored)
2. The README incorrectly referred to the file as `marc2bibframe.xspec`
Thanks for bringing this to our attention!
