### ISSUE TITLE
change bf:instrumentType to bf:instrumentalType

### ISSUE THREAD

**Issue by kirkhess** [lcnetdev/marc2bibframe2#99]
The property in the ontology is http://id.loc.gov/ontologies/bibframe.html#instrumentalType not bf:instrumentType. 

This is reflected in the specs:
http://www.loc.gov/bibframe/mtbf/ConvSpec-048-Codes-R0p.xlsx

And the conversion.
https://github.com/lcnetdev/marc2bibframe2/blob/4f3fcd3aa35280f1723a23cc5e216267e57bfffd/xsl/ConvSpec-010-048.xsl

**Comment by wafschneider** [comment]
Should we fix this ahead of the spec update? Seems like a simple typo in the specs.

**Comment by dbs** [comment]
See https://github.com/lcnetdev/marc2bibframe2/pull/102 for a fix, including a unit test.

**Comment by wafschneider** [comment]
Fixed in the v1.4.0 branch. Thanks for the fix and test, @dbs!
